version: "28.0.4"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=minibanco
      - POSTGRES_PASSWORD=039435
      - POSTGRES_DB= postgres
    volumes:
      - polls_pg_data:/bitnami/postgresql
